# Netlify configuration
[build]
  publish = "build"
  command = "npm run build"

# Node version configuration
[build.environment]
  NODE_VERSION = "18"

# Enable CORS headers to allow image loading from different origins
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
# Cache settings for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache settings for images
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache settings for PNG files
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 